services:
  - type: web
    name: be-todo
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        value: postgresql://tododb_jun9_user:kg3LfNlIN3HbwqYBBQ7164W9KC91OjiL@dpg-d7uppo9j2pic73c4vgfg-a/tododb_jun9
      - key: PORT
        value: 5000

  - type: web
    name: fe-todo
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: REACT_APP_API_URL
        value: https://be-todo-4wbs.onrender.com